INSERT INTO TB_CATEGORY (TITLE ) VALUES ('Ação');
INSERT INTO TB_CATEGORY (TITLE ) VALUES ('Aventura');
INSERT INTO TB_CATEGORY (TITLE ) VALUES ('Fantasia');

INSERT INTO TB_DEVELOPER (TITLE ) VALUES ('Fabricante 1');
INSERT INTO TB_DEVELOPER (TITLE ) VALUES ('Fabricante 2');

INSERT INTO TB_PLATFORM (TITLE) VALUES ('PC');
INSERT INTO TB_PLATFORM (TITLE) VALUES ('PS3');
INSERT INTO TB_PLATFORM (TITLE) VALUES ('XBOX');
INSERT INTO TB_PLATFORM (TITLE) VALUES ('PS4');
INSERT INTO TB_PLATFORM (TITLE) VALUES ('PS5');


INSERT INTO  TB_GAME (TITLE, DESCRIPTION, IMAGE_URL ,RELEASE_DATE,CATEGORY_ID,DEVELOPER_ID,PLATFORM_ID) VALUES ('God of War', 'jogo de aventura e ação', 'http://alguma lugar', '2002-01-25',1,1,1);
INSERT INTO  TB_GAME (TITLE, DESCRIPTION, IMAGE_URL ,RELEASE_DATE,CATEGORY_ID,DEVELOPER_ID,PLATFORM_ID) VALUES ('God of War 2', 'jogo de aventura e ação', 'http://alguma lugar', '2002-01-25',2,1,1);
INSERT INTO  TB_GAME (TITLE, DESCRIPTION, IMAGE_URL ,RELEASE_DATE,CATEGORY_ID,DEVELOPER_ID,PLATFORM_ID) VALUES ('God of War 3', 'jogo de aventura e ação', 'http://alguma lugar', '2002-01-25',2,1,2);

--INSERT INTO GAME_PLATFORM (GAME_ID, PLATFORM_ID) VALUES (1,2);
--INSERT INTO GAME_PLATFORM (GAME_ID, PLATFORM_ID) VALUES (1,1);
